default: &default
  adapter: postgresql
  encoding: utf8
  host : localhost
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: recruitment_task_development
  username: Edwardver
  password: 68631234q

test:
  <<: *default
  database: recruitment_task_test
  username: Edwardver
  password: 68631234q
